config/routes.rb
ComfyImprint::Engine.routes.draw do
  resources :contacts , only: [:index, :create, :new]
  get 'thank_you', to: 'contacts#thank_you'

  root to: "contacts#new"
end

app/models/comfy_imprint/contact.rb
module ComfyImprint
  class Contact < ActiveRecord::Base
    # You need to explictely set allow_blank: true on these validations, otherwise you'll run into a problem of blank values being invalid or too_short
    # See comfy_imprint/app/validators for custom validators used here


    validates :name,
              length: {minimum: 2,  maximum: 100},
              presence: {if: -> {ComfyImprint.configuration.attributes_to_require.include?(:name)}},
              allow_blank: {unless: -> {ComfyImprint.configuration.attributes_to_require.include?(:name)}},
              name: true
    validates :email,
              length: {minimum: 5,  maximum: 100},
              presence: {if: -> {ComfyImprint.configuration.attributes_to_require.include?(:email)}},
              allow_blank: {unless: -> {ComfyImprint.configuration.attributes_to_require.include?(:email)}},
              email: true
    validates :phone,
              length: {minimum: 10, maximum: 20},
              presence: {if: -> {ComfyImprint.configuration.attributes_to_require.include?(:phone)}},
              allow_blank: {unless: -> {ComfyImprint.configuration.attributes_to_require.include?(:phone)}},
              phone: true
    validates :company,
              length: {minimum: 2,  maximum: 200},
              presence: {if: -> {ComfyImprint.configuration.attributes_to_require.include?(:company)}},
              allow_blank: {unless: -> {ComfyImprint.configuration.attributes_to_require.include?(:company)}},
              company_name: true
    validates :url,
              length: {minimum: 5,  maximum: 200},
              presence: {if: -> {ComfyImprint.configuration.attributes_to_require.include?(:url)}},
              allow_blank: {unless: -> {ComfyImprint.configuration.attributes_to_require.include?(:url)}},
              url: true
    validates :is_subscribed,
              inclusion: {in: [true, false]},
              presence: {if: -> {ComfyImprint.configuration.attributes_to_require.include?(:is_subscribed)}},
              allow_blank: {unless: -> {ComfyImprint.configuration.attributes_to_require.include?(:is_subscribed)}}
    validates :message,
              length: {minimum: 5,  maximum: 1000},
              presence: {if: -> {ComfyImprint.configuration.attributes_to_require.include?(:message)}},
              allow_blank: {unless: -> {ComfyImprint.configuration.attributes_to_require.include?(:message)}},
              clean_text: true
  end
end

app/models/comfy_imprint/location.rb
module ComfyImprint
  class Location < ActiveRecord::Base
  end
end

app/controllers/comfy_imprint/application_controller.rb
class ComfyImprint::ApplicationController < ApplicationController
end

app/controllers/comfy_imprint/contacts_controller.rb
require_dependency "comfy_imprint/application_controller"

module ComfyImprint
  class ContactsController < ApplicationController
    before_filter :set_contact, only: [:show, :destroy]
    before_filter :find_locations

    def index
      redirect_to root_path
    end

    # GET /contacts/new
    def new
      @contact = Contact.new
    end

    # POST /contacts
    def create
      @contact = Contact.new(contact_params)
      if @contact.save
        # Contact Attempt passed validation so it's safe to mail it.
        # In the future I may want to implement some kind of delayed_job or redis hook here
        ContactMailer.contact_email(@contact).deliver
        redirect_to :thank_you #, notice: 'Contact was successfully created.'
      else
        render action: :new
      end
    end

    # DELETE /contacts/1
    def destroy
      @contact.destroy
      redirect_to contacts_url#, notice: 'Contact was successfully destroyed.'
    end

    def thank_you
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_contact
        @contact = Contact.find(params[:id])
      end

      def find_locations
        @locations = Location.all
      end

      # Only allow a trusted parameter "white list" through.
      def contact_params
        params.require(:contact).permit(:name, :email, :phone, 
        :url, :company, :is_subscribed, :message)
      end
  end
end

app/helpers/comfy_imprint/application_helper.rb
module ComfyImprint
  module ApplicationHelper
  end
end

app/helpers/comfy_imprint/contacts_helper.rb
module ComfyImprint
  module ContactsHelper
  end
end

app/views/admin/comfy_imprint/contacts/edit.html.haml
%h2
  = t('comfy_imprint.contact_us')
= render 'form'

app/views/admin/comfy_imprint/contacts/index.html.haml
%h2 Listing contacts
%table
  %thead
    %tr
      %th
      %th
      %th
  %tbody
    - @contacts.each do |contact|
      %tr
        %td= link_to 'Show', contact
        %td= link_to 'Edit', edit_contact_path(contact)
        %td= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Contact', new_contact_path

app/views/admin/comfy_imprint/contacts/new.html.haml
%h2
  = t('comfy_imprint.contact_us')
= render 'form'

app/views/admin/comfy_imprint/contacts/show.html.haml
%h2
  = t('comfy_imprint.contact_us')

= link_to 'Edit', edit_contact_path(@contact)
|
\#{link_to 'Back', contacts_path}

app/views/comfy_imprint/contacts/_form.html.haml
= simple_form_for(@contact, html: {class:'form-horizontal'}) do |f|
  - if @contact.errors.any?
    #error_explanation
      %h2
        = pluralize(@contact.errors.count, "error")
        prohibited this contact from being saved:
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg
  - ComfyImprint.configuration.attributes_to_display.each do |field|
    = f.input field

  = f.button :submit, class: 'button small'

app/views/comfy_imprint/contacts/_location.html.haml
%h3= location.name unless location.name.blank?
#comfy-imprint-location
  #snail-mail
    #address-lines
      = location.address_line_1 unless location.address_line_1.blank?
      = location.address_line_2 unless location.address_line_2.blank?
      = location.address_line_3 unless location.address_line_3.blank?
    #city-state-zip
      = location.city unless location.city.blank?
      = location.state unless location.state.blank?
      = location.zip unless location.zip.blank?
    #country
      = location.country unless location.country.blank?
    #attn
      = location.attn unless location.attn.blank?
  #note
    = location.note unless location.note.blank?
  #electronic-communications
    #phone-main
      = location.phone_main unless location.phone_main.blank?
    #phone-additional
      = location.phone_additional unless location.phone_additional.blank?
    #fax
      = location.fax unless location.fax.blank?
  #picture
    - unless location.picture_link.blank?
      %img{src: location.picture_link}
  #map
    - unless location.map_link.blank?
      %iframe{frameborder: '0', height: '400', marginheight: '0', marginwidth: '0', scrolling: 'no', width: '500', src: location.map_link }

app/views/comfy_imprint/contacts/_location_list.html.haml
-# Use this partial to layout your list of locations if you have a bunch.
-# It's not ideal to make a call to locations here and not in controller, but often times location list goes on a separte page or even in a footer or something:
-# Outside the scope of ComfyImprint. In that case you need to make a call to ComfyImprint::Location.all and pass it to partials.
- unless @locations.blank?
  %h2 Locations
  - @locations.each do |location|
    = render 'location', location: location

app/views/comfy_imprint/contacts/_number_800.html.haml
- unless ComfyImprint.configuration.number_800.blank?
  %h3
    = ComfyImprint.configuration.number_800

app/views/comfy_imprint/contacts/_social_badges.html.haml
#social_badges
  - unless ComfyImprint.configuration.social_badges.blank?
    - ComfyImprint.configuration.social_badges.each_pair do |badge, details|
      %div{id: "#{badge.to_s}_badge", class: 'social_badge'}
        = link_to details[:profile] do
          %img{src: "#{details[:logo]}"}

app/views/comfy_imprint/contacts/_submission.html.haml
- @contact.attributes.each do |key,val|
  - if ComfyImprint.configuration.attributes_to_display.include?(key.to_sym)
    .row
      %span.label
        %strong
          = "#{key.titleize} :"
      %span.value
        = val

app/views/comfy_imprint/contacts/new.html.haml
%h2
  = t('comfy_imprint.contact_us')
- ComfyImprint.configuration.sections_to_display.each do |section|
  = render section.to_s # In the future this allows to add more sections to display, and control them from config.

app/views/comfy_imprint/contacts/thank_you.html.haml
%h2
  = t('comfy_imprint.contact_us')
%h4
  = t('.notices.success')